### PR TITLE
Dev/v0.1.2

### PR DESCRIPTION
**Pull request by pierreguillot**

### CODE REVIEW

**Comment by agraef** [comment]
In case you didn't notice my final remark in #10: It would be nice if Faust could still be updated another time to 2.27.2. Unfortunately Stephane botched the 2.27.1 release (there were actually two versions of that), so just going with 2.27.2 would avoid any confusion about which Faust version pd-faustgen actually includes.

**Comment by agraef** [comment]
2.27.2 is here: https://github.com/grame-cncm/faust/releases/tag/2.27.2, it's revision https://github.com/grame-cncm/faust/commit/5c45bff8f7e83969426e7036b186b7715c3ecda0.

**Comment by agraef** [comment]
Great, many thanks! But why is https://github.com/CICM/pd-faustgen/releases/tag/v0.1.2 still a pre-release? Can you make it official?

**Comment by agraef** [comment]
Anyway, I updated my AUR packages now, and also contacted David on arch-proaudio so that we should hopefully see this release in the Arch community repository soon!

**Comment by pierreguillot** [comment]
> Great, many thanks! But why is https://github.com/CICM/pd-faustgen/releases/tag/v0.1.2 still a pre-release? Can you make it official?

I changed it :)

**Pull request merged**
